/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppBrandTemplateRouteImport } from './routes/_app.brand-template'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSpeakersRouteImport } from './routes/_app.speakers'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppSpeakersIdRouteImport } from './routes/_app.speakers.$id'
import { Route as AppProjectsIdClipsClipIdRouteImport } from './routes/_app.projects.$id.clips.$clipId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBrandTemplateRoute = AppBrandTemplateRouteImport.update({
  id: '/brand-template',
  path: '/brand-template',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeakersRoute = AppSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppSpeakersIdRoute = AppSpeakersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSpeakersRoute,
} as any)
const AppProjectsIdClipsClipIdRoute =
  AppProjectsIdClipsClipIdRouteImport.update({
    id: '/clips/$clipId',
    path: '/clips/$clipId',
    getParentRoute: () => AppProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-template': typeof AppBrandTemplateRoute
  '/home': typeof AppHomeRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/speakers': typeof AppSpeakersRouteWithChildren
  '/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/speakers/$id': typeof AppSpeakersIdRoute
  '/projects/$id/clips/$clipId': typeof AppProjectsIdClipsClipIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-template': typeof AppBrandTemplateRoute
  '/home': typeof AppHomeRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/speakers': typeof AppSpeakersRouteWithChildren
  '/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/speakers/$id': typeof AppSpeakersIdRoute
  '/projects/$id/clips/$clipId': typeof AppProjectsIdClipsClipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/brand-template': typeof AppBrandTemplateRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/speakers': typeof AppSpeakersRouteWithChildren
  '/_app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/_app/speakers/$id': typeof AppSpeakersIdRoute
  '/_app/projects/$id/clips/$clipId': typeof AppProjectsIdClipsClipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-template'
    | '/home'
    | '/projects'
    | '/settings'
    | '/speakers'
    | '/projects/$id'
    | '/speakers/$id'
    | '/projects/$id/clips/$clipId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-template'
    | '/home'
    | '/projects'
    | '/settings'
    | '/speakers'
    | '/projects/$id'
    | '/speakers/$id'
    | '/projects/$id/clips/$clipId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/brand-template'
    | '/_app/home'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/speakers'
    | '/_app/projects/$id'
    | '/_app/speakers/$id'
    | '/_app/projects/$id/clips/$clipId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/brand-template': {
      id: '/_app/brand-template'
      path: '/brand-template'
      fullPath: '/brand-template'
      preLoaderRoute: typeof AppBrandTemplateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/speakers': {
      id: '/_app/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof AppSpeakersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/speakers/$id': {
      id: '/_app/speakers/$id'
      path: '/$id'
      fullPath: '/speakers/$id'
      preLoaderRoute: typeof AppSpeakersIdRouteImport
      parentRoute: typeof AppSpeakersRoute
    }
    '/_app/projects/$id/clips/$clipId': {
      id: '/_app/projects/$id/clips/$clipId'
      path: '/clips/$clipId'
      fullPath: '/projects/$id/clips/$clipId'
      preLoaderRoute: typeof AppProjectsIdClipsClipIdRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
  }
}

interface AppProjectsIdRouteChildren {
  AppProjectsIdClipsClipIdRoute: typeof AppProjectsIdClipsClipIdRoute
}

const AppProjectsIdRouteChildren: AppProjectsIdRouteChildren = {
  AppProjectsIdClipsClipIdRoute: AppProjectsIdClipsClipIdRoute,
}

const AppProjectsIdRouteWithChildren = AppProjectsIdRoute._addFileChildren(
  AppProjectsIdRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRouteWithChildren
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRouteWithChildren,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppSpeakersRouteChildren {
  AppSpeakersIdRoute: typeof AppSpeakersIdRoute
}

const AppSpeakersRouteChildren: AppSpeakersRouteChildren = {
  AppSpeakersIdRoute: AppSpeakersIdRoute,
}

const AppSpeakersRouteWithChildren = AppSpeakersRoute._addFileChildren(
  AppSpeakersRouteChildren,
)

interface AppRouteChildren {
  AppBrandTemplateRoute: typeof AppBrandTemplateRoute
  AppHomeRoute: typeof AppHomeRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpeakersRoute: typeof AppSpeakersRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppBrandTemplateRoute: AppBrandTemplateRoute,
  AppHomeRoute: AppHomeRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSpeakersRoute: AppSpeakersRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
