/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as BrandTemplateRouteImport } from './routes/brand-template'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpeakersIdRouteImport } from './routes/speakers.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ProjectsIdClipsClipIdRouteImport } from './routes/projects.$id.clips.$clipId'

const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandTemplateRoute = BrandTemplateRouteImport.update({
  id: '/brand-template',
  path: '/brand-template',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersIdRoute = SpeakersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpeakersRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdClipsClipIdRoute = ProjectsIdClipsClipIdRouteImport.update({
  id: '/clips/$clipId',
  path: '/clips/$clipId',
  getParentRoute: () => ProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-template': typeof BrandTemplateRoute
  '/library': typeof LibraryRoute
  '/speakers': typeof SpeakersRouteWithChildren
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/speakers/$id': typeof SpeakersIdRoute
  '/projects/$id/clips/$clipId': typeof ProjectsIdClipsClipIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-template': typeof BrandTemplateRoute
  '/library': typeof LibraryRoute
  '/speakers': typeof SpeakersRouteWithChildren
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/speakers/$id': typeof SpeakersIdRoute
  '/projects/$id/clips/$clipId': typeof ProjectsIdClipsClipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-template': typeof BrandTemplateRoute
  '/library': typeof LibraryRoute
  '/speakers': typeof SpeakersRouteWithChildren
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/speakers/$id': typeof SpeakersIdRoute
  '/projects/$id/clips/$clipId': typeof ProjectsIdClipsClipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-template'
    | '/library'
    | '/speakers'
    | '/projects/$id'
    | '/speakers/$id'
    | '/projects/$id/clips/$clipId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-template'
    | '/library'
    | '/speakers'
    | '/projects/$id'
    | '/speakers/$id'
    | '/projects/$id/clips/$clipId'
  id:
    | '__root__'
    | '/'
    | '/brand-template'
    | '/library'
    | '/speakers'
    | '/projects/$id'
    | '/speakers/$id'
    | '/projects/$id/clips/$clipId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandTemplateRoute: typeof BrandTemplateRoute
  LibraryRoute: typeof LibraryRoute
  SpeakersRoute: typeof SpeakersRouteWithChildren
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-template': {
      id: '/brand-template'
      path: '/brand-template'
      fullPath: '/brand-template'
      preLoaderRoute: typeof BrandTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/$id': {
      id: '/speakers/$id'
      path: '/$id'
      fullPath: '/speakers/$id'
      preLoaderRoute: typeof SpeakersIdRouteImport
      parentRoute: typeof SpeakersRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/clips/$clipId': {
      id: '/projects/$id/clips/$clipId'
      path: '/clips/$clipId'
      fullPath: '/projects/$id/clips/$clipId'
      preLoaderRoute: typeof ProjectsIdClipsClipIdRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface SpeakersRouteChildren {
  SpeakersIdRoute: typeof SpeakersIdRoute
}

const SpeakersRouteChildren: SpeakersRouteChildren = {
  SpeakersIdRoute: SpeakersIdRoute,
}

const SpeakersRouteWithChildren = SpeakersRoute._addFileChildren(
  SpeakersRouteChildren,
)

interface ProjectsIdRouteChildren {
  ProjectsIdClipsClipIdRoute: typeof ProjectsIdClipsClipIdRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdClipsClipIdRoute: ProjectsIdClipsClipIdRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandTemplateRoute: BrandTemplateRoute,
  LibraryRoute: LibraryRoute,
  SpeakersRoute: SpeakersRouteWithChildren,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
