"""S3-compatible object storage backend.

All persistent media lives in the configured object storage bucket. The database
stores only object keys; services form public URLs by joining ``settings.s3_public_url``
with the key. Uploads are authorized via presigned PUT URLs generated by the
backend; neither the frontend nor the render service touches AK/SK.

Key layout:
- User upload: ``{user_id}/uploads/projects/{project_id}/{filename}``
- Speaker asset: ``{user_id}/speakers/{speaker_id}/{filename}``
- Brand media: ``{user_id}/brand-media/{filename}``
- Output: ``{user_id}/outputs/projects/{project_id}/{filename}``
- Demo user uses the ``demo/`` prefix instead of its UUID.
- Music library: ``music/{music_id}.{ext}``
"""

import asyncio
import base64
import mimetypes
import os
import tempfile
from pathlib import Path
from typing import Any, BinaryIO
from uuid import UUID

import boto3
import structlog
from botocore.config import Config
from botocore.exceptions import ClientError

from app.config import settings

logger = structlog.get_logger()

# The seeded default user shares the "demo" storage prefix so MVP assets live
# under the short, readable `demo/` tree instead of a long UUID path.
_DEFAULT_USER_ID = "00000000-0000-0000-0000-000000000001"
_DEMO_PROJECT_ID = "11111111-1111-1111-1111-111111111111"

_s3_client: Any | None = None


def _get_s3_client() -> boto3.client:
    """Return a cached boto3 S3 client configured for Volcengine TOS."""
    global _s3_client  # noqa: PLW0603
    if _s3_client is None:
        _s3_client = boto3.client(
            "s3",
            endpoint_url=settings.s3_endpoint_url,
            region_name=settings.s3_region,
            aws_access_key_id=settings.s3_access_key_id,
            aws_secret_access_key=settings.s3_secret_access_key,
            config=Config(
                signature_version="s3v4",
                s3={"addressing_style": "virtual"},
            ),
        )
    return _s3_client


def _storage_prefix(user_id: UUID | str) -> str:
    """Return the top-level directory name for a user's assets."""
    if str(user_id) == _DEFAULT_USER_ID:
        return "demo"
    return str(user_id)


def _is_demo_project(project_id: UUID | str) -> bool:
    return str(project_id) == _DEMO_PROJECT_ID


def _sanitize_filename(filename: str) -> str:
    """Sanitize upload filename to prevent path traversal.

    Strips directory components and replaces path separators.
    Falls back to 'unnamed' if the result is empty.
    """
    name = Path(filename).name
    name = name.replace("/", "_").replace("\\", "_")
    return name or "unnamed"


def _unique_key(prefix: str, filename: str) -> str:
    """Return a unique key under prefix, appending a counter if needed.

    Listing is expensive, so we append a short timestamp + random suffix instead
    of checking for existence on every call.
    """
    import secrets
    import time

    name = _sanitize_filename(filename)
    stem = Path(name).stem
    suffix = Path(name).suffix
    short = secrets.token_urlsafe(4)
    return f"{prefix}/{stem}-{int(time.time())}-{short}{suffix}"


def _normalize_key(key: str | None) -> str:
    """Strip leading slashes from a key."""
    return (key or "").lstrip("/")


# ---------------------------------------------------------------------------
# Path builders (now return object keys)
# ---------------------------------------------------------------------------


def get_project_upload_dir(project_id: UUID, user_id: UUID | str) -> str:
    """Get upload prefix for a project."""
    prefix = _storage_prefix(user_id)
    if _is_demo_project(project_id):
        return f"{prefix}/uploads"
    return f"{prefix}/uploads/projects/{project_id}"


def get_speaker_upload_dir(speaker_id: UUID, user_id: UUID | str) -> str:
    """Get upload prefix for a speaker."""
    return f"{_storage_prefix(user_id)}/speakers/{speaker_id}"


def get_brand_media_dir(user_id: UUID | str) -> str:
    """Get upload prefix for brand-template intro/outro media."""
    return f"{_storage_prefix(user_id)}/brand-media"


def get_project_output_dir(project_id: UUID, user_id: UUID | str) -> str:
    """Get output prefix for a project."""
    prefix = _storage_prefix(user_id)
    if _is_demo_project(project_id):
        return f"{prefix}/outputs"
    return f"{prefix}/outputs/projects/{project_id}"


async def get_upload_path(project_id: UUID, user_id: UUID | str, filename: str) -> str:
    """Generate a unique upload key for a project."""
    return _unique_key(get_project_upload_dir(project_id, user_id), filename)


async def get_speaker_upload_path(
    speaker_id: UUID,
    user_id: UUID | str,
    filename: str,
) -> str:
    """Generate a unique upload key for a speaker."""
    return _unique_key(get_speaker_upload_dir(speaker_id, user_id), filename)


async def get_brand_media_path(user_id: UUID | str, filename: str) -> str:
    """Generate a unique upload key for brand-template media."""
    return _unique_key(get_brand_media_dir(user_id), filename)


async def get_output_path(project_id: UUID, user_id: UUID | str, filename: str) -> str:
    """Generate an output key for a project."""
    prefix = get_project_output_dir(project_id, user_id)
    return f"{prefix}/{_sanitize_filename(filename)}"


# ---------------------------------------------------------------------------
# Public URLs
# ---------------------------------------------------------------------------


def public_url(key: str | None) -> str | None:
    """Return the public read URL for an object key."""
    if not key:
        return None
    base = settings.s3_public_url.rstrip("/")
    return f"{base}/{_normalize_key(key)}"


def resolve_stored_url(value: str | None) -> str | None:
    """Resolve a stored URL-or-key value to a browser-usable URL.

    DB columns hold bare object keys (new data) or legacy ``/api/v1/...`` paths
    (rows from before the object-storage migration). Bare keys are joined with
    the public URL base; absolute URLs and legacy API paths pass through
    unchanged so old rows keep working through the redirect endpoints.
    """
    if not value:
        return value
    if value.startswith(("http://", "https://", "/")):
        return value
    return public_url(value)


def stream_url(key: str | None) -> str | None:
    """Browser-playable URL for an uploaded source file."""
    return public_url(key)


def output_url(key: str | None) -> str | None:
    """Browser-playable URL for a rendered output."""
    return public_url(key)


def music_url(mood: str | None) -> str | None:
    """Legacy mood-track endpoint URL (still served by /api/v1/music/{mood})."""
    if not mood:
        return None
    return f"/api/v1/music/{mood}"


def music_stream_url(music_id: UUID | str | None) -> str | None:
    """Stream URL for a Music row (served by /api/v1/music/{music_id}/stream)."""
    if music_id is None or str(music_id) == "":
        return None
    return f"/api/v1/music/{music_id}/stream"


# ---------------------------------------------------------------------------
# Upload / download / delete
# ---------------------------------------------------------------------------


async def presign_upload(
    key: str,
    content_type: str | None = None,
    *,
    ttl: int | None = None,
) -> str:
    """Generate a presigned PUT URL for direct upload to object storage."""
    client = _get_s3_client()
    params: dict[str, str] = {
        "Bucket": settings.s3_bucket_name,
        "Key": _normalize_key(key),
    }
    if content_type:
        params["ContentType"] = content_type
    expires_in = ttl if ttl is not None else settings.s3_presign_upload_ttl
    return await asyncio.to_thread(
        client.generate_presigned_url,
        "put_object",
        Params=params,
        ExpiresIn=expires_in,
    )


async def presign_download(
    key: str,
    *,
    filename: str | None = None,
    ttl: int = 300,
) -> str:
    """Generate a presigned GET URL for an object.

    When ``filename`` is given, the response carries
    ``Content-Disposition: attachment; filename*=UTF-8''<name>`` so the browser
    downloads instead of playing inline (the plain public URL cannot do this).
    """
    client = _get_s3_client()
    params: dict[str, str] = {
        "Bucket": settings.s3_bucket_name,
        "Key": _normalize_key(key),
    }
    if filename:
        from urllib.parse import quote

        params["ResponseContentDisposition"] = (
            f"attachment; filename*=UTF-8''{quote(filename)}"
        )
    return await asyncio.to_thread(
        client.generate_presigned_url,
        "get_object",
        Params=params,
        ExpiresIn=ttl,
    )


async def save(key: str, data: bytes | BinaryIO, content_type: str | None = None) -> str:
    """Upload bytes or a file-like object to object storage and return the key."""
    client = _get_s3_client()
    body = data if isinstance(data, bytes) else data.read()
    params: dict[str, object] = {
        "Bucket": settings.s3_bucket_name,
        "Key": _normalize_key(key),
        "Body": body,
    }
    if content_type:
        params["ContentType"] = content_type
    await asyncio.to_thread(client.put_object, **params)
    return key


async def save_upload(
    file_obj: BinaryIO,
    project_id: UUID,
    user_id: UUID | str,
    filename: str,
) -> str:
    """Save uploaded file to project storage and return the object key."""
    key = await get_upload_path(project_id, user_id, filename)
    return await save(key, file_obj)


async def save_speaker_upload(
    file_obj: BinaryIO,
    speaker_id: UUID,
    user_id: UUID | str,
    filename: str,
) -> str:
    """Save uploaded file to speaker storage and return the object key."""
    key = await get_speaker_upload_path(speaker_id, user_id, filename)
    return await save(key, file_obj)


async def save_brand_media_upload(
    file_obj: BinaryIO,
    user_id: UUID | str,
    filename: str,
) -> str:
    """Save an intro/outro image or video and return its object key."""
    key = await get_brand_media_path(user_id, filename)
    return await save(key, file_obj)


async def save_output(
    project_id: UUID,
    user_id: UUID | str,
    filename: str,
    content: bytes,
) -> str:
    """Save output bytes to project storage and return the object key."""
    key = await get_output_path(project_id, user_id, filename)
    return await save(key, content)


async def read(key: str) -> bytes:
    """Read an object's bytes from storage."""
    client = _get_s3_client()
    response = await asyncio.to_thread(
        client.get_object,
        Bucket=settings.s3_bucket_name,
        Key=_normalize_key(key),
    )
    return await asyncio.to_thread(response["Body"].read)


async def download_to_temp(key: str | None) -> Path | None:
    """Download an object to a temporary file and return its path.

    Streams to disk via ``download_file`` (no full-object memory buffering), so
    it is safe for multi-GB source videos. The caller is responsible for
    deleting the temp file.
    """
    if not key:
        return None
    client = _get_s3_client()
    suffix = Path(key).suffix or ""
    fd, tmp_path = tempfile.mkstemp(suffix=suffix)
    os.close(fd)
    try:
        await asyncio.to_thread(
            client.download_file,
            settings.s3_bucket_name,
            _normalize_key(key),
            tmp_path,
        )
        return Path(tmp_path)
    except Exception:
        Path(tmp_path).unlink(missing_ok=True)
        raise


async def delete(key: str | None) -> None:
    """Delete a single object by key."""
    if not key:
        return
    client = _get_s3_client()
    await asyncio.to_thread(
        client.delete_object,
        Bucket=settings.s3_bucket_name,
        Key=_normalize_key(key),
    )


async def delete_file(key: str | None) -> None:
    """Alias for delete(), matching the legacy storage API."""
    await delete(key)


async def _list_keys(prefix: str) -> list[str]:
    """List all object keys under a prefix."""
    client = _get_s3_client()
    paginator = client.get_paginator("list_objects_v2")
    keys: list[str] = []
    for page in await asyncio.to_thread(
        lambda: list(
            paginator.paginate(Bucket=settings.s3_bucket_name, Prefix=prefix)
        ),
    ):
        for obj in page.get("Contents", []):
            keys.append(obj["Key"])
    return keys


async def delete_prefix(prefix: str) -> None:
    """Delete all objects under a prefix."""
    keys = await _list_keys(prefix)
    if not keys:
        return
    client = _get_s3_client()
    # S3 delete_objects accepts up to 1000 keys per call.
    for i in range(0, len(keys), 1000):
        batch = [{"Key": k} for k in keys[i : i + 1000]]
        await asyncio.to_thread(
            client.delete_objects,
            Bucket=settings.s3_bucket_name,
            Delete={"Objects": batch},
        )


async def delete_project_files(project_id: UUID, user_id: UUID | str) -> None:
    """Delete all files for a project."""
    await delete_prefix(get_project_upload_dir(project_id, user_id))
    await delete_prefix(get_project_output_dir(project_id, user_id))


async def delete_speaker_files(speaker_id: UUID, user_id: UUID | str) -> None:
    """Delete all files for a speaker."""
    await delete_prefix(get_speaker_upload_dir(speaker_id, user_id))


# ---------------------------------------------------------------------------
# Compatibility helpers
# ---------------------------------------------------------------------------


def owner_from_path(key: str | None) -> str | None:
    """Extract the owning user id (or 'demo') from a stored object key."""
    if not key:
        return None
    first = key.strip("/").split("/", 1)[0]
    return first if first else None


def _is_not_found(e: ClientError) -> bool:
    """True when the S3 error means the object simply does not exist."""
    return e.response.get("Error", {}).get("Code") in ("404", "NoSuchKey", "NotFound")


async def exists(key: str | None) -> bool:
    """Return True if the object exists in storage.

    Only a missing object yields False; credential/network errors propagate so
    callers (e.g. seed reconcilers) do not silently misread them as "absent".
    """
    if not key:
        return False
    client = _get_s3_client()
    try:
        await asyncio.to_thread(
            client.head_object,
            Bucket=settings.s3_bucket_name,
            Key=_normalize_key(key),
        )
        return True
    except ClientError as e:
        if _is_not_found(e):
            return False
        raise


async def size(key: str | None) -> int | None:
    """Return the object size in bytes, or None if missing (404 only)."""
    if not key:
        return None
    client = _get_s3_client()
    try:
        response = await asyncio.to_thread(
            client.head_object,
            Bucket=settings.s3_bucket_name,
            Key=_normalize_key(key),
        )
        return int(response["ContentLength"])
    except ClientError as e:
        if _is_not_found(e):
            return None
        raise


def resolve_file_path(key: str | None) -> Path | None:
    """Compatibility alias: download an object to a temp file.

    Legacy callers expected a local Path under asset_dir. Under S3-only storage
    we download to a temp file and return that path. The caller must delete it.
    """
    # download_to_temp is async; this synchronous wrapper is intentionally
    # limited. Callers should migrate to await download_to_temp(key).
    if not key:
        return None

    try:
        return asyncio.run(download_to_temp(key))
    except RuntimeError:
        return None


def file_to_data_url(path_or_key: str | Path | None) -> str | None:
    """Return a base64 data URL for a local file or an object key.

    Accepts either a legacy Path or an object key. For object keys, the bytes
    are fetched from storage synchronously (best-effort for legacy sync callers).
    """
    if path_or_key is None:
        return None

    raw: bytes | None = None
    mime = "application/octet-stream"

    if isinstance(path_or_key, Path):
        path = path_or_key
        if not path.is_file():
            return None
        try:
            raw = path.read_bytes()
        except OSError:
            return None
        guessed, _ = mimetypes.guess_type(str(path))
        if guessed:
            mime = guessed
    else:
        key = str(path_or_key)
        try:
            raw = asyncio.run(read(key))
        except Exception:
            return None
        guessed, _ = mimetypes.guess_type(key)
        if guessed:
            mime = guessed

    if raw is None:
        return None
    encoded = base64.b64encode(raw).decode("ascii")
    return f"data:{mime};base64,{encoded}"
