"""add_chat_sessions_refactor_messages

Revision ID: 01d5ed9e3af2
Revises: 0bbee17b0c18
Create Date: 2026-07-06 14:12:11.904699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01d5ed9e3af2'
down_revision: Union[str, Sequence[str], None] = '0bbee17b0c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_asset_id'), 'chat_sessions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_project_id'), 'chat_sessions', ['project_id'], unique=False)
    op.drop_table('human_feedback')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    # MVP migration: old messages schema is replaced; clear existing rows.
    op.execute("DELETE FROM messages")
    op.add_column('messages', sa.Column('session_id', sa.UUID(), nullable=False))
    op.add_column('messages', sa.Column('workflow_run_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('intent', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_messages_asset_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_asset_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_project_id'), table_name='messages')
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.drop_constraint(op.f('messages_project_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_parent_message_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'workflow_runs', ['workflow_run_id'], ['id'])
    op.drop_column('messages', 'meta')
    op.drop_column('messages', 'project_id')
    op.drop_column('messages', 'asset_id')
    op.drop_column('messages', 'parent_message_id')
    op.drop_column('messages', 'asset_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('asset_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('parent_message_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_parent_message_id_fkey'), 'messages', 'messages', ['parent_message_id'], ['id'])
    op.create_foreign_key(op.f('messages_project_id_fkey'), 'messages', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.create_index(op.f('ix_messages_project_id'), 'messages', ['project_id'], unique=False)
    op.create_index(op.f('ix_messages_asset_type'), 'messages', ['asset_type'], unique=False)
    op.create_index(op.f('ix_messages_asset_id'), 'messages', ['asset_id'], unique=False)
    op.drop_column('messages', 'intent')
    op.drop_column('messages', 'workflow_run_id')
    op.drop_column('messages', 'session_id')
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_table('human_feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('clip_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('human_feedback_clip_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('human_feedback_pkey'))
    )
    op.drop_index(op.f('ix_chat_sessions_project_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_asset_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
