"""drop_clip_script_remove_shots

Revision ID: 0b19cd023b4a
Revises: 01d5ed9e3af2
Create Date: 2026-07-06 15:12:07.004297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b19cd023b4a'
down_revision: Union[str, Sequence[str], None] = '01d5ed9e3af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clips', 'script')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('script', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
