"""add assets.user_id and messages.asset_id/asset_type

Revision ID: 0bbee17b0c18
Revises: 7e4f3ad9dae9
Create Date: 2026-07-03 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbee17b0c18'
down_revision: Union[str, Sequence[str], None] = '7e4f3ad9dae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DEFAULT_USER_ID = "00000000-0000-0000-0000-000000000001"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # assets.user_id: nullable first, backfill from owning project/speaker, then enforce.
    op.add_column('assets', sa.Column('user_id', sa.UUID(), nullable=True))
    op.execute(
        "UPDATE assets "
        "SET user_id = COALESCE("
        "  (SELECT user_id FROM projects WHERE projects.id = assets.project_id),"
        "  (SELECT user_id FROM speakers WHERE speakers.id = assets.speaker_id),"
        f"  '{DEFAULT_USER_ID}'"
        ")"
    )
    op.alter_column('assets', 'user_id', nullable=False)
    op.create_foreign_key(None, 'assets', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)

    # messages.asset_id / asset_type for asset-scoped chat.
    op.add_column('messages', sa.Column('asset_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('asset_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_messages_asset_id'), 'messages', ['asset_id'], unique=False)
    op.create_index(op.f('ix_messages_asset_type'), 'messages', ['asset_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_asset_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_asset_id'), table_name='messages')
    op.drop_column('messages', 'asset_type')
    op.drop_column('messages', 'asset_id')

    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'user_id')
    # ### end Alembic commands ###
