"""drop unused workflow_steps

Revision ID: 8565f7764dc8
Revises: e8347ed87fcf
Create Date: 2026-06-26 20:41:34.418194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8565f7764dc8'
down_revision: Union[str, Sequence[str], None] = 'e8347ed87fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_steps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_steps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('step_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('input_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], name=op.f('workflow_steps_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_steps_pkey'))
    )
    # ### end Alembic commands ###
