"""add users and user_id ownership

Revision ID: 8898ca9f9ca1
Revises: ec6a3114994c
Create Date: 2026-07-01 21:21:18.999324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8898ca9f9ca1'
down_revision: Union[str, Sequence[str], None] = 'ec6a3114994c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema and seed a default user."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    # Seed the default user that owns all existing data in the no-login MVP.
    default_user_id = "00000000-0000-0000-0000-000000000001"
    users_table = sa.table(
        "users",
        sa.column("id", sa.UUID()),
        sa.column("email", sa.String()),
        sa.column("name", sa.String()),
    )
    op.bulk_insert(users_table, [
        {
            "id": default_user_id,
            "email": "default@repurposer.local",
            "name": "Default User",
        }
    ])

    # Add nullable user_id columns first, backfill existing rows, then enforce NOT NULL.
    op.add_column('brand_templates', sa.Column('user_id', sa.UUID(), nullable=True))
    op.execute(f"UPDATE brand_templates SET user_id = '{default_user_id}'")
    op.alter_column('brand_templates', 'user_id', nullable=False)
    op.create_foreign_key(None, 'brand_templates', 'users', ['user_id'], ['id'])

    op.add_column('projects', sa.Column('user_id', sa.UUID(), nullable=True))
    op.execute(f"UPDATE projects SET user_id = '{default_user_id}'")
    op.alter_column('projects', 'user_id', nullable=False)
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])

    op.add_column('speakers', sa.Column('user_id', sa.UUID(), nullable=True))
    op.execute(f"UPDATE speakers SET user_id = '{default_user_id}'")
    op.alter_column('speakers', 'user_id', nullable=False)
    op.create_foreign_key(None, 'speakers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'speakers', type_='foreignkey')
    op.drop_column('speakers', 'user_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    op.drop_constraint(None, 'brand_templates', type_='foreignkey')
    op.drop_column('brand_templates', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
