"""asset duration + meta for ASR

Revision ID: 90154b458822
Revises: 99efa033eb5c
Create Date: 2026-06-27 02:16:53.893805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90154b458822'
down_revision: Union[str, Sequence[str], None] = '99efa033eb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'meta')
    op.drop_column('assets', 'duration_seconds')
    # ### end Alembic commands ###
