"""add speaker content_strategy

Revision ID: c3d1ef0d4373
Revises: 7a3f9c1e2b8d
Create Date: 2026-07-13 12:04:52.599928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d1ef0d4373'
down_revision: Union[str, Sequence[str], None] = '7a3f9c1e2b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('voice', sa.String(length=255), nullable=True))
    op.add_column('speakers', sa.Column('audience', sa.String(length=255), nullable=True))
    op.add_column('speakers', sa.Column('guidelines', sa.Text(), nullable=True))
    op.add_column('speakers', sa.Column('cta', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speakers', 'cta')
    op.drop_column('speakers', 'guidelines')
    op.drop_column('speakers', 'audience')
    op.drop_column('speakers', 'voice')
    # ### end Alembic commands ###
