"""flatten speaker persona into columns

Revision ID: d46403707861
Revises: c3d1ef0d4373
Create Date: 2026-07-13 15:13:29.282364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd46403707861'
down_revision: Union[str, Sequence[str], None] = 'c3d1ef0d4373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema and migrate legacy persona JSON."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('core_values', sa.JSON(), nullable=True))
    op.add_column('speakers', sa.Column('favorite_metaphors', sa.JSON(), nullable=True))
    op.add_column('speakers', sa.Column('sentence_style', sa.String(length=255), nullable=True))
    op.add_column('speakers', sa.Column('emotional_tone', sa.String(length=20), nullable=True))
    op.add_column('speakers', sa.Column('typical_hooks', sa.JSON(), nullable=True))
    op.add_column('speakers', sa.Column('avoid_words', sa.JSON(), nullable=True))
    # voice/audience/guidelines/cta already added by c3d1ef0d4373 (this
    # migration's own parent) — not re-added here, just backfilled below.

    # Migrate legacy persona JSON into new flat columns before dropping it.
    connection = op.get_bind()
    metadata = sa.MetaData()
    speakers = sa.Table('speakers', metadata, autoload_with=connection)

    for row in connection.execute(sa.select(speakers.c.id, speakers.c.persona)):
        raw = row.persona or {}
        # Legacy data was either flat or nested under a "persona" key.
        if "persona" in raw and isinstance(raw["persona"], dict):
            style = raw["persona"]
            memory = raw
        else:
            style = raw
            memory = raw

        updates = {
            "core_values": style.get("core_values") or [],
            "favorite_metaphors": style.get("favorite_metaphors") or [],
            "sentence_style": style.get("sentence_style") or "",
            "emotional_tone": style.get("emotional_tone") or "rational",
            "typical_hooks": style.get("typical_hooks") or [],
            "avoid_words": style.get("avoid_words") or [],
        }
        for key in ("voice", "audience", "guidelines", "cta"):
            value = memory.get(key)
            if value is not None:
                updates[key] = value

        connection.execute(
            sa.update(speakers).where(speakers.c.id == row.id).values(**updates)
        )

    op.drop_column('speakers', 'persona')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('persona', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # voice/audience/guidelines/cta are owned by c3d1ef0d4373 — dropped there.
    op.drop_column('speakers', 'avoid_words')
    op.drop_column('speakers', 'typical_hooks')
    op.drop_column('speakers', 'emotional_tone')
    op.drop_column('speakers', 'sentence_style')
    op.drop_column('speakers', 'favorite_metaphors')
    op.drop_column('speakers', 'core_values')
    # ### end Alembic commands ###
