"""Music library service: CRUD + generation + default-catalog seeding + in-use guard.

Audio bytes live in object storage under ``music/{music_id}.{ext}``; this layer
owns the DB rows, the MiniMax generation call (media generation via the Model
boundary is legal at the Graph layer — same class as the image calls in
``pipeline/images.py``), and the object-vs-row lifecycle. Deletion refuses a
piece still referenced by any clip's ``render_spec.music`` (the 3 default
pieces are also protected this way).
"""

from dataclasses import dataclass
from uuid import NAMESPACE_DNS, UUID, uuid4, uuid5

import httpx
import structlog
from sqlalchemy import or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.clients.minimax import MiniMaxError, minimax_client
from app.metering import record_media_usage
from app.models.tables import Music, Output
from app.providers.storage import delete, exists, save, size

logger = structlog.get_logger()

# ---- object-storage mechanics ----------------------------------------------
# The generated piece's bytes are persisted under ``music/{music_id}.{ext}``
# in object storage; the ``Music`` row's ``file_path`` is that object key.
# Bytes never live in the DB. (通用件随消费方，N-42 批④：音乐库消费侧即本层。)

AUDIO_EXT = "mp3"


@dataclass(frozen=True)
class GeneratedMusic:
    """A generated music piece ready to persist."""

    audio_bytes: bytes
    ext: str
    duration_seconds: int | None
    size_bytes: int
    model: str
    generation_id: str | None


def music_file_path(music_id: UUID) -> str:
    """Return the object storage key for a music piece's audio file."""
    return f"music/{music_id}.{AUDIO_EXT}"


async def persist_music(music_id: UUID, generated: GeneratedMusic) -> tuple[str, int]:
    """Upload generated audio bytes to object storage.

    Returns (object_key, size). The key is ``music/{music_id}.{ext}``.
    """
    key = music_file_path(music_id)
    await save(key, generated.audio_bytes, content_type="audio/mpeg")
    return key, len(generated.audio_bytes)


async def music_disk_path(music_id: UUID) -> bool:
    """Return whether the music object exists in storage.

    Kept as an async compatibility shim for code that used ``music_disk_path``
    to check file existence.
    """
    return await exists(music_file_path(music_id))

# Quality model for committed platform defaults; free model for ad-hoc user
# generation to control cost (see docs/MUSIC_ARCHITECTURE.md).
DEFAULTS_MODEL = "music-2.6"
USER_MODEL = "music-2.6-free"


async def generate_music(
    prompt: str,
    *,
    model: str = USER_MODEL,
    is_instrumental: bool = True,
) -> GeneratedMusic:
    """Generate a music piece via MiniMax and download the bytes.

    The native ``/v1/music_generation`` call (see ``clients/minimax.py``)
    returns a short-lived audio URL, so the bytes are downloaded immediately.

    Raises ``MiniMaxError`` on any API/download failure.
    """
    result = await minimax_client.generate_music(
        prompt,
        model=model,
        is_instrumental=is_instrumental,
        output_format="url",
        audio_format=AUDIO_EXT,
    )
    if not result.audio_url:
        raise MiniMaxError("MiniMax music generation returned no audio URL")
    await record_media_usage({"music_pieces": 1.0})

    async with httpx.AsyncClient(timeout=120) as client:
        dl = await client.get(result.audio_url)
        dl.raise_for_status()
        audio_bytes = dl.content

    duration_seconds = (
        int(result.duration_ms // 1000) if result.duration_ms is not None else None
    )
    size = result.size_bytes if result.size_bytes else len(audio_bytes)
    logger.info(
        "music_generated",
        model=model,
        duration_seconds=duration_seconds,
        size_bytes=size,
        generation_id=result.generation_id,
    )
    return GeneratedMusic(
        audio_bytes=audio_bytes,
        ext=AUDIO_EXT,
        duration_seconds=duration_seconds,
        size_bytes=size,
        model=model,
        generation_id=result.generation_id,
    )


class MusicInUseError(Exception):
    """Raised when deleting a music piece still referenced by clips."""

    def __init__(self, music_id: UUID, count: int) -> None:
        self.music_id = music_id
        self.count = count
        super().__init__(f"Music {music_id} is referenced by {count} clip(s)")


# The 3 platform-default pieces. ``id`` is a deterministic uuid5 so the same
# piece always lands on ``music/{id}.mp3`` whether it is generated by the
# one-time seed script or reconciled by ``seed_default_music``.
DEFAULT_MUSIC_CATALOG: list[dict[str, str]] = [
    {
        "mood": "calm",
        "title": "Calm Academic",
        "prompt": (
            "Minimal ambient piano, no vocals, calm and intellectual, "
            "background music for an academic speech, 60 seconds, seamless loop"
        ),
    },
    {
        "mood": "uplifting",
        "title": "Inspiring Vision",
        "prompt": (
            "Inspiring orchestral strings with gentle piano, no vocals, "
            "uplifting and hopeful, cinematic, 60 seconds, seamless loop"
        ),
    },
    {
        "mood": "corporate",
        "title": "Corporate Drive",
        "prompt": (
            "Modern corporate electronic beat, no vocals, confident and "
            "professional, steady mid-tempo, 60 seconds, seamless loop"
        ),
    },
]


def default_music_id(mood: str) -> UUID:
    """Deterministic UUID for a default-catalog piece (stable across runs)."""
    return uuid5(NAMESPACE_DNS, f"repurposer:music:{mood}")


async def list_music(db: AsyncSession, user_id: UUID | None = None) -> list[Music]:
    """List public music pieces plus the caller's own private pieces."""
    where_clause = Music.is_public.is_(True)
    if user_id is not None:
        where_clause = or_(where_clause, Music.generated_by_user_id == user_id)
    result = await db.execute(
        select(Music).where(where_clause).order_by(Music.created_at.desc())
    )
    return list(result.scalars().all())


async def get_music(db: AsyncSession, music_id: UUID) -> Music | None:
    """Get a music piece by id."""
    return await db.get(Music, music_id)


async def get_music_by_mood(db: AsyncSession, mood: str) -> Music | None:
    """Get a music piece by its unique mood natural key."""
    result = await db.execute(select(Music).where(Music.mood == mood))
    return result.scalar_one_or_none()


async def create_music_from_generation(
    db: AsyncSession,
    *,
    prompt: str,
    generated: GeneratedMusic,
    mood: str | None = None,
    title: str | None = None,
    user_id: UUID | None = None,
    license: str | None = None,
    source_url: str | None = None,
    attribution: str | None = None,
    is_public: bool = True,
) -> Music:
    """Persist generated audio to object storage and create the DB row.

    ``mood`` is the unique natural key; when omitted a ``custom-<short>`` key is
    derived from the new id. A mood collision with an existing piece is
    suffixed to keep the column unique.
    """
    music_id = uuid4()
    base_mood = (mood or f"custom-{music_id.hex[:8]}").strip().lower()
    if await get_music_by_mood(db, base_mood) is not None:
        base_mood = f"{base_mood}-{music_id.hex[:4]}"
    title = title or _default_title(prompt, base_mood)

    file_path, size_bytes = await persist_music(music_id, generated)
    music = Music(
        id=music_id,
        mood=base_mood,
        title=title,
        ext=generated.ext,
        file_path=file_path,
        size_bytes=size_bytes,
        duration_seconds=generated.duration_seconds,
        prompt=prompt,
        model=generated.model,
        generation_id=generated.generation_id,
        license=license,
        source_url=source_url,
        attribution=attribution,
        is_public=is_public,
        generated_by_user_id=user_id,
    )
    db.add(music)
    await db.commit()
    await db.refresh(music)
    logger.info("music_created", music_id=str(music_id), mood=base_mood, user_id=str(user_id))
    return music


async def update_music_metadata(
    db: AsyncSession,
    music_id: UUID,
    *,
    title: str | None = None,
    license: str | None = None,
    source_url: str | None = None,
    attribution: str | None = None,
    is_public: bool | None = None,
) -> Music | None:
    """Update editable metadata fields; returns None if the piece doesn't exist."""
    music = await db.get(Music, music_id)
    if music is None:
        return None
    if title is not None:
        music.title = title
    if license is not None:
        music.license = license
    if source_url is not None:
        music.source_url = source_url
    if attribution is not None:
        music.attribution = attribution
    if is_public is not None:
        music.is_public = is_public
    await db.commit()
    await db.refresh(music)
    return music


async def is_music_in_use(db: AsyncSession, music_id: UUID) -> int:
    """Count clip outputs whose render_spec.music references this piece.

    Portable Python-side scan (works on both Postgres and the SQLite test DB).
    On Postgres this could be a single JSONB-containment query; the library is
    small enough that the scan is fine and keeps tests dialect-agnostic.
    """
    target = str(music_id)
    result = await db.execute(
        select(Output.render_spec).where(Output.render_spec.isnot(None))
    )
    count = 0
    for (spec,) in result.all():
        if not isinstance(spec, dict):
            continue
        music = spec.get("music")
        if not isinstance(music, dict):
            continue
        # New contract: music_id; legacy: track_id (both carry the piece id).
        if music.get("music_id") == target or music.get("track_id") == target:
            count += 1
    return count


async def delete_music(db: AsyncSession, music_id: UUID) -> Music | None:
    """Delete a music piece's DB row and object storage file.

    Raises ``MusicInUseError`` (→ 409) if any clip references it. Returns the
    deleted row (for response shaping) or None if the piece doesn't exist.
    """
    music = await db.get(Music, music_id)
    if music is None:
        return None
    in_use = await is_music_in_use(db, music_id)
    if in_use > 0:
        raise MusicInUseError(music_id, in_use)
    await delete(music.file_path)
    await db.delete(music)
    await db.commit()
    logger.info("music_deleted", music_id=str(music_id), mood=music.mood)
    return music


async def seed_default_music(db: AsyncSession) -> list[Music]:
    """Reconcile the 3 default pieces with objects in storage.

    Idempotent: for each catalog mood, if a row already exists, skip; if the
    audio object ``music/{default_music_id(mood)}.mp3`` exists, create the row
    pointing at it; otherwise skip (the one-time seed script generates + uploads
    the files). No MiniMax call here.
    """
    created: list[Music] = []
    for entry in DEFAULT_MUSIC_CATALOG:
        mood = entry["mood"]
        if await get_music_by_mood(db, mood) is not None:
            continue
        music_id = default_music_id(mood)
        key = music_file_path(music_id)
        try:
            object_exists = await music_disk_path(music_id)
        except Exception as e:  # noqa: BLE001 — storage unreachable at startup
            logger.error("seed_default_music_check_failed", mood=mood, error=str(e))
            continue
        if not object_exists:
            logger.warning("seed_default_music_missing_object", mood=mood, key=key)
            continue
        file_size = await size(key) or 0
        music = Music(
            id=music_id,
            mood=mood,
            title=entry["title"],
            ext=AUDIO_EXT,
            file_path=key,
            size_bytes=file_size,
            prompt=entry["prompt"],
            model=DEFAULTS_MODEL,
            is_public=True,
            generated_by_user_id=None,
        )
        db.add(music)
        created.append(music)
    if created:
        await db.commit()
        for m in created:
            await db.refresh(m)
        logger.info("seed_default_music_created", count=len(created))
    return created


def _default_title(prompt: str, mood: str) -> str:
    """Best-effort title for a generated piece from its prompt/mood."""
    stripped = prompt.strip().splitlines()[0] if prompt.strip() else mood
    return stripped[:80] if stripped else mood


__all__ = [
    "AUDIO_EXT",
    "DEFAULT_MUSIC_CATALOG",
    "DEFAULTS_MODEL",
    "MusicInUseError",
    "USER_MODEL",
    "create_music_from_generation",
    "default_music_id",
    "delete_music",
    "generate_music",
    "get_music",
    "get_music_by_mood",
    "is_music_in_use",
    "list_music",
    "seed_default_music",
    "update_music_metadata",
]
