"""Music library service: CRUD + default-catalog seeding + in-use guard.

Audio bytes live on disk under ``assets/music/{music_id}.{ext}`` (see
``services/music_generation.py``); this layer owns the DB rows and the
file-vs-row lifecycle. Deletion refuses a piece still referenced by any clip's
``render_spec.music`` (the 3 default pieces are also protected this way).
"""

from uuid import NAMESPACE_DNS, UUID, uuid4, uuid5

import structlog
from sqlalchemy import or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models.tables import Clip, Music
from app.services.music_generation import (
    AUDIO_EXT,
    DEFAULTS_MODEL,
    GeneratedMusic,
    music_disk_path,
    music_file_path,
    persist_music,
)

logger = structlog.get_logger()


class MusicInUseError(Exception):
    """Raised when deleting a music piece still referenced by clips."""

    def __init__(self, music_id: UUID, count: int) -> None:
        self.music_id = music_id
        self.count = count
        super().__init__(f"Music {music_id} is referenced by {count} clip(s)")


# The 3 platform-default pieces. ``id`` is a deterministic uuid5 so the same
# piece always lands on ``assets/music/{id}.mp3`` whether it is generated by the
# one-time seed script (task #17) or reconciled by ``seed_default_music``.
DEFAULT_MUSIC_CATALOG: list[dict[str, str]] = [
    {
        "mood": "calm",
        "title": "Calm Academic",
        "prompt": (
            "Minimal ambient piano, no vocals, calm and intellectual, "
            "background music for an academic speech, 60 seconds, seamless loop"
        ),
    },
    {
        "mood": "uplifting",
        "title": "Inspiring Vision",
        "prompt": (
            "Inspiring orchestral strings with gentle piano, no vocals, "
            "uplifting and hopeful, cinematic, 60 seconds, seamless loop"
        ),
    },
    {
        "mood": "corporate",
        "title": "Corporate Drive",
        "prompt": (
            "Modern corporate electronic beat, no vocals, confident and "
            "professional, steady mid-tempo, 60 seconds, seamless loop"
        ),
    },
]


def default_music_id(mood: str) -> UUID:
    """Deterministic UUID for a default-catalog piece (stable across runs)."""
    return uuid5(NAMESPACE_DNS, f"repurposer:music:{mood}")


async def list_music(db: AsyncSession, user_id: UUID | None = None) -> list[Music]:
    """List public music pieces plus the caller's own private pieces."""
    where_clause = Music.is_public.is_(True)
    if user_id is not None:
        where_clause = or_(where_clause, Music.generated_by_user_id == user_id)
    result = await db.execute(
        select(Music).where(where_clause).order_by(Music.created_at.desc())
    )
    return list(result.scalars().all())


async def get_music(db: AsyncSession, music_id: UUID) -> Music | None:
    """Get a music piece by id."""
    return await db.get(Music, music_id)


async def get_music_by_mood(db: AsyncSession, mood: str) -> Music | None:
    """Get a music piece by its unique mood natural key."""
    result = await db.execute(select(Music).where(Music.mood == mood))
    return result.scalar_one_or_none()


async def create_music_from_generation(
    db: AsyncSession,
    *,
    prompt: str,
    generated: GeneratedMusic,
    mood: str | None = None,
    title: str | None = None,
    user_id: UUID | None = None,
    license: str | None = None,
    source_url: str | None = None,
    attribution: str | None = None,
    is_public: bool = True,
) -> Music:
    """Persist generated audio to disk and create the DB row.

    ``mood`` is the unique natural key; when omitted a ``custom-<short>`` key is
    derived from the new id. A mood collision with an existing piece is
    suffixed to keep the column unique.
    """
    music_id = uuid4()
    base_mood = (mood or f"custom-{music_id.hex[:8]}").strip().lower()
    if await get_music_by_mood(db, base_mood) is not None:
        base_mood = f"{base_mood}-{music_id.hex[:4]}"
    title = title or _default_title(prompt, base_mood)

    file_path, size = persist_music(music_id, generated)
    music = Music(
        id=music_id,
        mood=base_mood,
        title=title,
        ext=generated.ext,
        file_path=file_path,
        size_bytes=size,
        duration_seconds=generated.duration_seconds,
        prompt=prompt,
        model=generated.model,
        generation_id=generated.generation_id,
        license=license,
        source_url=source_url,
        attribution=attribution,
        is_public=is_public,
        generated_by_user_id=user_id,
    )
    db.add(music)
    await db.commit()
    await db.refresh(music)
    logger.info("music_created", music_id=str(music_id), mood=base_mood, user_id=str(user_id))
    return music


async def update_music_metadata(
    db: AsyncSession,
    music_id: UUID,
    *,
    title: str | None = None,
    license: str | None = None,
    source_url: str | None = None,
    attribution: str | None = None,
    is_public: bool | None = None,
) -> Music | None:
    """Update editable metadata fields; returns None if the piece doesn't exist."""
    music = await db.get(Music, music_id)
    if music is None:
        return None
    if title is not None:
        music.title = title
    if license is not None:
        music.license = license
    if source_url is not None:
        music.source_url = source_url
    if attribution is not None:
        music.attribution = attribution
    if is_public is not None:
        music.is_public = is_public
    await db.commit()
    await db.refresh(music)
    return music


async def is_music_in_use(db: AsyncSession, music_id: UUID) -> int:
    """Count clips whose render_spec.music references this piece.

    Portable Python-side scan (works on both Postgres and the SQLite test DB).
    On Postgres this could be a single JSONB-containment query; the library is
    small enough that the scan is fine and keeps tests dialect-agnostic.
    """
    target = str(music_id)
    result = await db.execute(
        select(Clip.render_spec).where(Clip.render_spec.isnot(None))
    )
    count = 0
    for (spec,) in result.all():
        if not isinstance(spec, dict):
            continue
        music = spec.get("music")
        if not isinstance(music, dict):
            continue
        # New contract: music_id; legacy: track_id (both carry the piece id).
        if music.get("music_id") == target or music.get("track_id") == target:
            count += 1
    return count


async def delete_music(db: AsyncSession, music_id: UUID) -> Music | None:
    """Delete a music piece's DB row and on-disk file.

    Raises ``MusicInUseError`` (→ 409) if any clip references it. Returns the
    deleted row (for response shaping) or None if the piece doesn't exist.
    """
    music = await db.get(Music, music_id)
    if music is None:
        return None
    in_use = await is_music_in_use(db, music_id)
    if in_use > 0:
        raise MusicInUseError(music_id, in_use)
    path = settings.asset_dir / music.file_path
    if path.is_file():
        path.unlink()
    await db.delete(music)
    await db.commit()
    logger.info("music_deleted", music_id=str(music_id), mood=music.mood)
    return music


async def seed_default_music(db: AsyncSession) -> list[Music]:
    """Reconcile the 3 default pieces with committed files on disk.

    Idempotent: for each catalog mood, if a row already exists, skip; if the
    audio file ``assets/music/{default_music_id(mood)}.mp3`` exists, create the
    row pointing at it; otherwise skip (the one-time seed script in task #17
    generates + commits the files). No MiniMax call here.
    """
    created: list[Music] = []
    for entry in DEFAULT_MUSIC_CATALOG:
        mood = entry["mood"]
        if await get_music_by_mood(db, mood) is not None:
            continue
        music_id = default_music_id(mood)
        disk_path = music_disk_path(music_id)
        if not disk_path.is_file():
            logger.warning("seed_default_music_missing_file", mood=mood, path=str(disk_path))
            continue
        music = Music(
            id=music_id,
            mood=mood,
            title=entry["title"],
            ext=AUDIO_EXT,
            file_path=music_file_path(music_id),
            size_bytes=disk_path.stat().st_size,
            prompt=entry["prompt"],
            model=DEFAULTS_MODEL,
            is_public=True,
            generated_by_user_id=None,
        )
        db.add(music)
        created.append(music)
    if created:
        await db.commit()
        for m in created:
            await db.refresh(m)
        logger.info("seed_default_music_created", count=len(created))
    return created


def _default_title(prompt: str, mood: str) -> str:
    """Best-effort title for a generated piece from its prompt/mood."""
    stripped = prompt.strip().splitlines()[0] if prompt.strip() else mood
    return stripped[:80] if stripped else mood


__all__ = [
    "AUDIO_EXT",
    "DEFAULT_MUSIC_CATALOG",
    "DEFAULTS_MODEL",
    "MusicInUseError",
    "create_music_from_generation",
    "default_music_id",
    "delete_music",
    "get_music",
    "get_music_by_mood",
    "is_music_in_use",
    "list_music",
    "seed_default_music",
    "update_music_metadata",
]
