"""Upload recipe-card teaser assets to TOS with content-hashed keys and
regenerate the web manifest (apps/web/src/lib/recipes.assets.ts).

Usage:
    uv run python scripts/upload_recipe_assets.py <dir-with-asset-files>

Files in the dir keep their logical names (dub-preview.mp4, style-poster.jpg…);
each is uploaded to demo/outputs/<stem>-<md5:8><ext> and the manifest is
rewritten with the new URLs. Files not present keep their existing manifest
entry, so partial re-renders are fine.

Why content-hashed keys: Chrome's media cache never revalidates <video> range
requests (not even on hard refresh), so overwriting a stable key leaves stale
MP4s playing — a manual ?v=N bump fixed this once and was immediately rejected
as a step people will forget. Content-addressed URLs make correct caching
structural: objects ship Cache-Control immutable (1y) and the URL changes
exactly when the content does.
"""

import asyncio
import hashlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.config import settings  # noqa: E402
from app.tools.storage import _get_s3_client, public_url  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[3]
MANIFEST = REPO_ROOT / "apps/web/src/lib/recipes.assets.ts"
PREFIX = "demo/outputs"
CONTENT_TYPES = {".mp4": "video/mp4", ".jpg": "image/jpeg"}
IMMUTABLE = "public, max-age=31536000, immutable"
ENTRY_RE = re.compile(r'"([^"]+)":\s*"([^"]+)"')


def _read_manifest_entries() -> dict[str, str]:
    if not MANIFEST.exists():
        return {}
    return dict(ENTRY_RE.findall(MANIFEST.read_text()))


def _write_manifest(entries: dict[str, str]) -> None:
    lines = [
        "/**",
        " * GENERATED by apps/api/scripts/upload_recipe_assets.py — do not edit.",
        " * Content-hashed URLs for the recipe-card teasers (consumed by lib/recipes.ts).",
        " */",
        "export const RECIPE_ASSETS = {",
    ]
    for name in sorted(entries):
        lines.append(f'  "{name}": "{entries[name]}",')
    lines.append("} as const")
    lines.append("")
    MANIFEST.write_text("\n".join(lines))


async def main() -> None:
    if len(sys.argv) < 2:
        raise SystemExit(f"usage: {Path(__file__).name} <dir-of-mp4/jpg-assets>")
    src_dir = Path(sys.argv[1])
    files = sorted(p for p in src_dir.iterdir() if p.suffix in CONTENT_TYPES)
    if not files:
        raise SystemExit(f"no asset files (.mp4/.jpg) in {src_dir}")

    client = _get_s3_client()
    entries = _read_manifest_entries()
    for path in files:
        digest = hashlib.md5(path.read_bytes()).hexdigest()[:8]
        key = f"{PREFIX}/{path.stem}-{digest}{path.suffix}"
        await asyncio.to_thread(
            client.put_object,
            Bucket=settings.s3_bucket_name,
            Key=key,
            Body=path.read_bytes(),
            ContentType=CONTENT_TYPES[path.suffix],
            CacheControl=IMMUTABLE,
        )
        url = public_url(key)
        assert url is not None  # s3_public_url is configured
        entries[path.name] = url
        print(f"{path.name} -> {entries[path.name]}")

    _write_manifest(entries)
    print(f"manifest: {MANIFEST} ({len(entries)} entries)")


if __name__ == "__main__":
    asyncio.run(main())
