/**
 * GENERATED by apps/api/scripts/upload_recipe_assets.py — do not edit.
 * Content-hashed URLs for the recipe-card teasers (consumed by lib/recipes.ts).
 */
export const RECIPE_ASSETS = {
  "ai-visuals-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/ai-visuals-poster-d45b3114.jpg",
  "dub-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/dub-poster-5535321b.jpg",
  "dub-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/dub-preview-ba2a2ea7.mp4",
  "image-video-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/image-video-poster-103ceb64.jpg",
  "image-video-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/image-video-preview-34f88e57.mp4",
  "reframe-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/reframe-poster-69e5d0ce.jpg",
  "reframe-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/reframe-preview-6af9eb86.mp4",
  "style-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/style-poster-cad259dc.jpg",
  "style-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/style-preview-a330fe7d.mp4",
} as const
