/**
 * 配方卡 (RecipeCard, RECIPES §7.1) — the home capability gallery, fed by the
 * server-side recipe registry (dual-end architecture, 2026-08-01):
 *
 * - **Structural data** (id / status / input_slots) comes from the public
 *   `GET /api/v1/recipes` — the pin substance (task book) never leaves the
 *   server, so a card's promise can only be delivered by mentioning it.
 * - **Preview assets** live in the content-hashed map below (recipes.assets.ts,
 *   GENERATED by apps/api/scripts/upload_recipe_assets.py).
 * - **Copy** lives in i18n under `recipes.<id>.*` (title / promise /
 *   promptTemplate).
 *
 * Adding a recipe = a server registry entry + i18n keys + a preview asset —
 * three configurations, zero code paths.
 */

import { apiFetch } from "@/lib/api"
import { RECIPE_ASSETS } from "@/lib/recipes.assets"

/** Public card shape served by `GET /api/v1/recipes` (same name, same shape
 * as the backend `RecipePublic`, NAMING §1). */
export interface RecipePublic {
  id: string
  status: "live" | "reserved"
  input_slots: { type: string; required: boolean }[]
}

export interface RecipeCard extends RecipePublic {
  /** Public-readable assets on the TOS demo tree (demo/outputs/) — the landing
   * audience is anonymous, so signed/login-gated asset endpoints are banned. */
  preview: { posterUrl: string; videoUrl?: string }
}

/** Content-hashed teaser URLs — the URL changes exactly when the content
 * does, so objects cache immutably and stale media-cache copies are
 * impossible by construction. */
const asset = (name: keyof typeof RECIPE_ASSETS) => RECIPE_ASSETS[name]

/** Card id → teaser assets (display layer only — never enters the pipeline). */
const RECIPE_PREVIEWS: Record<string, RecipeCard["preview"]> = {
  dub: {
    posterUrl: asset("dub-poster.jpg"),
    videoUrl: asset("dub-preview.mp4"),
  },
  "image-video": {
    posterUrl: asset("image-video-poster.jpg"),
    videoUrl: asset("image-video-preview.mp4"),
  },
  reframe: {
    posterUrl: asset("reframe-poster.jpg"),
    videoUrl: asset("reframe-preview.mp4"),
  },
  style: {
    posterUrl: asset("style-poster.jpg"),
    videoUrl: asset("style-preview.mp4"),
  },
  "ai-visuals": {
    posterUrl: asset("ai-visuals-poster.jpg"),
    // No preview video until the capability itself exists — poster only.
  },
}

/** The gallery's card list: the public registry joined with preview assets.
 * Cards without a preview entry are skipped (a card never renders half-dressed). */
export async function fetchRecipeCards(): Promise<RecipeCard[]> {
  const res = await apiFetch("/api/v1/recipes")
  if (!res.ok) return []
  const recipes = (await res.json()) as RecipePublic[]
  return recipes.flatMap((r) => {
    const preview = RECIPE_PREVIEWS[r.id]
    return preview ? [{ ...r, preview }] : []
  })
}
