/**
 * GENERATED by apps/api/scripts/upload_recipe_assets.py — do not edit.
 * Content-hashed URLs for the recipe-card teasers (consumed by lib/recipes.ts).
 */
export const RECIPE_ASSETS = {
  "ai-visuals-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/ai-visuals-poster-d45b3114.jpg",
  "comparison-after.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/comparison-after-cca9916b.mp4",
  "comparison-source.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/comparison-source-cf674a39.mp4",
  "dub-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/dub-poster-5535321b.jpg",
  "dub-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/dub-preview-ba2a2ea7.mp4",
  "highlight-clips-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/highlight-clips-poster-11bc0ca3.jpg",
  "highlight-clips-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/highlight-clips-preview-ec8e575b.mp4",
  "image-video-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/image-video-poster-2b1a8f81.jpg",
  "image-video-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/image-video-preview-18833859.mp4",
  "multilingual-subs-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/multilingual-subs-poster-9268b24e.jpg",
  "multilingual-subs-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/multilingual-subs-preview-26f850f0.mp4",
  "reframe-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/reframe-poster-c4eec0b0.jpg",
  "reframe-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/reframe-preview-7bcbb54e.mp4",
  "style-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/style-poster-cad259dc.jpg",
  "style-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/style-preview-a330fe7d.mp4",
  "talking-head-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/talking-head-poster-494deafa.jpg",
} as const
