/**
 * GENERATED by apps/api/scripts/upload_recipe_assets.py — do not edit.
 * Content-hashed URLs for the recipe-card teasers (consumed by lib/recipes.ts).
 */
export const RECIPE_ASSETS = {
  "ai-visuals-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/ai-visuals-poster-d45b3114.jpg",
  "comparison-after.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/comparison-after-cca9916b.mp4",
  "comparison-source.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/comparison-source-cf674a39.mp4",
  "dub-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/dub-poster-5535321b.jpg",
  "dub-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/dub-preview-ba2a2ea7.mp4",
  "image-video-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/image-video-poster-b715a075.jpg",
  "image-video-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/image-video-preview-818e015e.mp4",
  "reframe-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/reframe-poster-8644f689.jpg",
  "reframe-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/reframe-preview-cca9916b.mp4",
  "style-poster.jpg": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/style-poster-cad259dc.jpg",
  "style-preview.mp4": "https://repurposer.tos-ap-southeast-1.volces.com/demo/outputs/style-preview-a330fe7d.mp4",
} as const
