/**
 * 配方卡 (RecipeCard, RECIPES §7.1) — the home capability gallery, fed by the
 * server-side recipe registry. **配方 = 数据** (2026-08-06): the server holds
 * one data package per recipe — base structure / flow / example_assets /
 * example_outputs ride the public endpoint (the preset substance never
 * leaves the server); translatable text stays in i18n (`recipes.<id>.*`
 * plus the shared `recipes.flow.*` / `recipes.tags.*` / `recipes.materials.*`
 * namespaces); the card-face teaser lives in the content-hashed map below
 * (recipes.assets.ts, GENERATED by apps/api/scripts/upload_recipe_assets.py).
 *
 * Adding a recipe = one server registry entry (the data package) + i18n keys
 * + a teaser asset — zero code paths.
 */

import { apiFetch } from "@/lib/api"
import { RECIPE_ASSETS } from "@/lib/recipes.assets"

/** Public card shape served by `GET /api/v1/recipes` (same name, same shape
 * as the backend `RecipePublic`, NAMING §1). */
export interface RecipePublic {
  id: string
  status: "live" | "reserved"
  input_slots: { type: string; required: boolean }[]
  aspect: string
  /** Shared `recipes.tags.*` i18n keys. */
  tags: string[]
  /** Static recipe flow (ADR-035): shared `recipes.flow.*` i18n keys. */
  flow: { key: string; detail_key?: string | null; fanout?: number | null }[]
  example_assets: { kind: string; url: string; label_key?: string | null }[]
  example_outputs: {
    kind: string
    url: string
    poster_url?: string | null
    label_key?: string | null
  }[]
}

export interface RecipeCard extends RecipePublic {
  /** Public-readable assets on the TOS demo tree (demo/outputs/) — the landing
   * audience is anonymous, so signed/login-gated asset endpoints are banned. */
  preview: { posterUrl: string; videoUrl?: string }
}

/** Does a staged file cover a required input slot? The launch gate reads
 * this (a recipe's required blank must be filled before send — same posture
 * as the composer's prompt-required toast). Mirrors inferAssetType's MIME
 * families; slides travel as deck files (pdf/ppt). */
export function slotCoversFile(slotType: string, file: File): boolean {
  switch (slotType) {
    case "video":
      return file.type.startsWith("video/")
    case "audio":
      return file.type.startsWith("audio/")
    case "images":
      return file.type.startsWith("image/")
    case "slides":
      return (
        file.type === "application/pdf" ||
        /\.(pdf|pptx?|key)$/i.test(file.name)
      )
    default:
      // transcript — the document/text fallback, same as inferAssetType.
      return !/^(video|audio|image)\//.test(file.type)
  }
}

/** Content-hashed teaser URLs — the URL changes exactly when the content
 * does, so objects cache immutably and stale media-cache copies are
 * impossible by construction. */
const asset = (name: keyof typeof RECIPE_ASSETS) => RECIPE_ASSETS[name]

/** Card id → teaser assets (display layer only — never enters the pipeline). */
const RECIPE_PREVIEWS: Record<string, RecipeCard["preview"]> = {
  "multilingual-subs": {
    posterUrl: asset("multilingual-subs-poster.jpg"),
    // The baked 1:1 contrast pack's CN-EN bilingual version — two-line
    // translated captions on the card face state the capability before a
    // word is read.
    videoUrl: asset("multilingual-subs-preview.mp4"),
  },
  "image-video": {
    posterUrl: asset("image-video-poster.jpg"),
    videoUrl: asset("image-video-preview.mp4"),
  },
  "highlight-clips": {
    posterUrl: asset("highlight-clips-poster.jpg"),
    videoUrl: asset("highlight-clips-preview.mp4"),
  },
  reframe: {
    posterUrl: asset("reframe-poster.jpg"),
    videoUrl: asset("reframe-preview.mp4"),
  },
  "ai-visuals": {
    posterUrl: asset("ai-visuals-poster.jpg"),
    // No preview video until the capability itself exists — poster only.
  },
}

/** The gallery's card list: the public registry joined with preview assets.
 * Cards without a preview entry are skipped (a card never renders half-dressed). */
export async function fetchRecipeCards(): Promise<RecipeCard[]> {
  const res = await apiFetch("/api/v1/recipes")
  if (!res.ok) return []
  const recipes = (await res.json()) as RecipePublic[]
  return recipes.flatMap((r) => {
    const preview = RECIPE_PREVIEWS[r.id]
    return preview ? [{ ...r, preview }] : []
  })
}
